### ISSUE TITLE
Seeing Apps in "My Work" area under Children in the Mashup UI

### ISSUE THREAD

**Issue by rajivmaskara** [mindspank/architeqt#6]
Hi Alex, 

Great concept I must admit. 

I was planning on demoing it and this little bit came up while building a usecase for it.
This is more of a feature request than a bug and of course you may choose to completely ignore this.

Anyways, currently only published apps with some value in UseBlueprint appear in the UI under children. 

Ideally, I would like to use an app template before I start my development work, before publishing it anywhere. Once the template is applied, I would then begin the development work.

The current UI does not allow me to apply a template to an app in My Work area because it does not get listed under children, even if I have updated the UseBlueprint property in QMC.

I hope the usecase makes sense to you and would consider making this change??

Cheers,
Rajiv Maskara

**Comment by mindspank** [comment]
I'm actively disabling syncing to unpublished apps. Partially because it's kinda strange having published items in a unpublished app but also because I don't really see the use case.

I could see a value in being able to sync dimensions/measures to a unpublished app but I also see that being able to sync to unpublished apps promote a QlikView workflow in Qlik Sense which I don't want to enable.

Short story, I don't see a good enough self-service use-case to lift the restriction but maybe you have one :)

-----Original Message-----
